version: '3.0'

expectations:
 population_size: 20000

actions:

  generate_dataset_cases:
    run: >
      databuilder:v0 
        generate-dataset analysis/dataset_definition_cases.py --output output/dataset_cases.csv.gz
    outputs:
      highly_sensitive:
        dataset_cases: output/dataset_cases.csv.gz
  
  generate_dataset_controls:
    run: >
      databuilder:v0 
        generate-dataset analysis/dataset_definition_controls.py --output output/dataset_controls.csv.gz
    outputs:
      highly_sensitive:
        dataset_controls: output/dataset_controls.csv.gz
  
  generate_dataset_lc_pre_vacc:
    run: >
      databuilder:v0 
        generate-dataset analysis/dataset_definition_longcovid_prevaccine.py --output output/dataset_lc_pre_vacc.csv.gz
    outputs:
      highly_sensitive:
        dataset_controls: output/dataset_lc_pre_vacc.csv.gz
  
  clean_the_data: 
    run: > 
      r:latest
        analysis/010_cleandata.R
    needs: [generate_dataset_cases, generate_dataset_controls]
    outputs: 
      highly_sensitive:
        cleandata: output/clean_dataset.gz.parquet 
      moderately_sensitive: 
        txt1: output/data_properties/raw_dataset_skim.txt
        txt2: output/data_properties/raw_dataset_tabulate.txt
        txt3: output/data_properties/clean_dataset_skim.txt
        txt4: output/data_properties/clean_dataset_tabulate.txt

  clean_lc_pre_vacc_data: 
    run: >
      r:latest
        analysis/0101_clean_lcfirst_cohort.R
    needs: [generate_dataset_lc_pre_vacc]
    outputs: 
      highly_sensitive: 
        cleandata_lcfirst: output/clean_dataset_lc_first.gz.parquet
      moderately_sensitive: 
        txt5: output/data_properties/lcfirst_cohort_skim.txt
        txt6: output/data_properties/lcfirst_cohort_tabulate.txt
        tab1_lc_first: output/tables/tab1_full_description_lc_first.html
  
  plot_vaccine_after_longcovid: 
    run: >
      r:latest
        analysis/0102_vaccine_after_longcovid.R
    needs: [clean_lc_pre_vacc_data, clean_the_data]
    outputs: 
      moderately_sensitive: 
        vaccine_pct_plot: output/figures/fig6_vaccine_after_lc.pdf
        vaccine_pct_data: output/lc_first_vaccination.csv

  time_update_data: 
    run: >
      r:latest
        analysis/011_timeupdate_data.R
    needs: [clean_the_data]
    outputs: 
      highly_sensitive: 
        timedata_longcovid: output/timeupdate_dataset_lc_all.gz.parquet
        timedata_longcovid_dx: output/timeupdate_dataset_lc_dx.gz.parquet
        timedata_covidhosp: output/timeupdate_dataset_covidhosp.gz.parquet
      moderately_sensitive: 
        txt3: output/data_properties/timeupdated_dataset_skim.txt

  summarise_timedata: 
    run: >
      r:latest
        analysis/012_timeupdated_summary.R
    needs: [time_update_data]
    outputs: 
      moderately_sensitive: 
        txt4: output/data_properties/timeupdated_lc_all_tabulate.txt
        lc_all_t_plot: output/supplementary/time_updated_t_byvaccines.pdf
        lc_dx_t_plot: output/supplementary/time_updated_t_byvaccines_lc_dx.pdf
  
  summarise_cohort_at_baseline: 
    run: >
      r:latest
        analysis/013_create_table1.R
    needs: [clean_the_data]
    outputs: 
      moderately_sensitive: 
        table1: output/tables/tab1_baseline_description.html
        table1_csv: output/tab1_baseline_data.csv
        table2: output/tables/tab2_fup_description.html
        table2_csv: output/tab2_fup_data.csv
        vaccine_lc_gap: output/supplementary/fig_vaccines_longcovid_gap.pdf
        vaccine_lc_gap_detail: output/supplementary/fig_vaccines_longcovid_gap_zoomed.pdf
        vaccine_lc_gap_csv: output/supplementary/vaccines_longcovid_gap.csv
        

  calculate_monthly_dynamics: 
    run: > 
      r:latest
        analysis/014_calculate_monthly_dynamics.R
    needs: [clean_the_data]
    outputs: 
      moderately_sensitive: 
        monthly_dynamics: output/data_monthly_dynamics.csv
        table_monthly_dynamics: output/tables/supptab01_monthly_dynamics.csv
  
  calculate_daily_dynamics: 
    run: > 
      r:latest
        analysis/015_calculate_daily_dynamics.R
    needs: [clean_the_data]
    outputs: 
      moderately_sensitive: 
        daily_dynamics: output/data_daily_dynamics.csv

  crude_rates_timeupdated:
    run: >
      r:latest
        analysis/021_cruderates_timeupdated.R
    needs: [time_update_data]
    outputs:
      moderately_sensitive:
        t_cruderates_lc_all: output/tab022_tuv_rates_lc_all.csv
        t_cruderates_lc_dx: output/tab023_tuv_rates_lc_dx.csv
  
  output_crude_rates:
    run: >
      r:latest
        analysis/022_combine_cruderates.R
    needs: [crude_rates_timeupdated]
    outputs:
      moderately_sensitive:
        cruderates_redacted: output/tables/tab3_crude_rates_redacted.csv
        cruderates_plot: output/figures/fig3_crude_rates.pdf
  
  plot_incidence:
    run: >
      r:latest
        analysis/030_plotrates.R
    needs: [time_update_data]
    outputs:
      moderately_sensitive:
        counts_line: output/figures/fig2_raw_counts_line.pdf
        counts_line_sex: output/figures/fig2a_raw_counts_line_bysex.pdf
        countscolumn: output/figures/fig2b_raw_counts_column.pdf
        countscolumn_sex: output/figures/fig2c_raw_counts_column_bysex.pdf
        stackedbar: output/figures/fig2e_longcovid_stacked_dx_rx.pdf
        multipanelfig: output/figures/fig2_longcovid_dynamics.pdf
        vaccinegap: output/supplementary/fig_agegap_vaccines.pdf

  longcovid_by_snomedcode:
    run: >
      r:latest
        analysis/031_longcovid_by_snomedcode.R
    needs: [clean_the_data]
    outputs:
      moderately_sensitive:
        tab_snomedcode_count: output/tables/tab5_snomedcode_count.csv
        fig_snomedcode_over_time: output/figures/fig2f_raw_counts_by_code.pdf
        tab_snomedcode_over_time: output/raw_counts_by_code_over_time.csv

  plot_longcovid_flows:
    run: >
      r:latest
        analysis/032_pathways_to_longcovid.R
    needs: [clean_the_data]
    outputs:
      moderately_sensitive:
        tests_lc_table: output/tables/tab_tests_and_longcovid.html
        tests_density: output/supplementary/test_to_longcovid_density.pdf
        longcovid_flows: output/figures/fig5_longcovid_flows.pdf
        longcovid_flows_data: output/sankey_plot_data.csv
        demographics_by_test_status: output/tables/tab_demographics_by_test_status.html
        demographics_by_test_status_csv: output/data_demographics_by_test_status.csv
        demographics_by_dx_rx_tbl: output/tables/tab_demographics_by_dx_rx.html
        demographics_by_dx_rx_csv: output/data_demographics_by_dx_rx.csv
  
  plot_daily_dynamics:
    run: >
      r:latest
        analysis/033_plot_daily_dynamics.R
    needs: [calculate_daily_dynamics]
    outputs:
      moderately_sensitive:
        dailydynamics_plot: output/figures/fig2g_daily_cases.pdf
        dailydynamics_data: output/data_daily_dynamics_plot.csv
  
  plot_monthly_dynamics:
    run: >
      r:latest
        analysis/034_plot_monthly_dynamics.R
    needs: [calculate_monthly_dynamics]
    outputs:
      moderately_sensitive:
        monthly_plot_v1: output/figures/fig4a_outbreak_dynamics.pdf
        monthly_plot_v2: output/figures/fig4b_outbreak_dynamics_cumulative.pdf
        monthly_plot_v3: output/figures/fig4c_outbreak_dynamics_experimental.pdf
        monthly_plot_v4: output/figures/fig4d_outbreak_dynamics_log.pdf
        monthly_plot_v5: output/figures/fig4e_longcovid_and_national_cases.pdf

  poisson_checks:
    run: >
      r:latest
        analysis/040_poisson_checks.R
    needs: [clean_the_data, time_update_data]
    outputs:
      moderately_sensitive:
        clean_poissonchecks: output/data_properties/poisson_checks/clean_data_poisson_checks.txt
        clean_conditional_poisson_check: output/data_properties/poisson_checks/clean_data_poisson_checks.csv
        tup1_poissonchecks: output/data_properties/poisson_checks/time_data_lc_dx_poisson_checks.txt
        tup1_conditional_poisson_check: output/data_properties/poisson_checks/time_data_lc_dx_poisson_checks.csv
        tup2_poissonchecks: output/data_properties/poisson_checks/time_data_lc_first_poisson_checks.txt
        tup2_conditional_poisson_check: output/data_properties/poisson_checks/time_data_lc_first_poisson_checks.csv
        poisson_hist: output/data_properties/poisson_checks/poisson_hist.pdf
        
  poisson_rates_timeupdated:
    run: >
      r:latest
        analysis/041_poisson_regressions_timeupdated.R
    needs: [clean_the_data, time_update_data]
    outputs:
      moderately_sensitive:
        poissonrates: output/tab023_poissonrates_timeupdated.csv
        model_outputs1: output/regression_outputs/model_out_age_cat.txt
        model_outputs2: output/regression_outputs/model_out_sex.txt
        model_outputs3: output/regression_outputs/model_out_t_vacc_mrna.txt
        model_outputs4: output/regression_outputs/model_out_vaccines.txt
 
  poisson_plots:
    run: >
      r:latest
        analysis/042_plot_poisson_results.R
    needs: [poisson_rates_timeupdated]
    outputs: 
      moderately_sensitive: 
        fig3a: output/figures/fig3a_crude_RRs.pdf
        fig3b: output/figures/fig3b_adjusted_RRs.pdf
        fig3e: output/figures/fig3e_vaccines.pdf
        poissonplots_table: output/tables/tab4_poisson_rateratios.csv


## Sensitivity analyses
  time_update_sensAnalysis: 
    run: >
      r:latest
        analysis/015_timeupdate_data_sensAnalysis.R
    needs: [clean_the_data]
    outputs: 
      highly_sensitive: 
        timedata_longcovid_sensAnalysis_12wks: output/timeupdate_dataset_lc_all_sensAnalysis_12wks.gz.parquet
        timedata_longcovid_sensAnalysis_4wks: output/timeupdate_dataset_lc_all_sensAnalysis_4wks.gz.parquet
        timedata_longcovid_dx_sensAnalysis_12wks: output/timeupdate_dataset_lc_dx_sensAnalysis_12wks.gz.parquet
        timedata_longcovid_dx_sensAnalysis_4wks: output/timeupdate_dataset_lc_dx_sensAnalysis_4wks.gz.parquet
        timedata_covid_hosp_sensAnalysis_2wks: output/timeupdate_dataset_covidhosp_sensAnalysis_2wks.gz.parquet
  
  poisson_rates_timeupdated_sensAnalysis:
    run: >
      r:latest
        analysis/043_poisson_regressions_timeupdated_sensAnalysis.R
    needs: [clean_the_data, time_update_sensAnalysis]
    outputs:
      moderately_sensitive:
        poissonrates: output/tab023_poissonrates_timeupdated_sensAnalysis.csv

  poisson_plots_sensAnalysis:
    run: >
      r:latest
        analysis/044_plot_poisson_results_sensAnalyses.R
    needs: [poisson_rates_timeupdated_sensAnalysis, poisson_rates_timeupdated]
    outputs: 
      moderately_sensitive: 
        fig3a_sensAnalyses: output/figures/fig3a_crude_RRs_sensAnalysis.pdf
        fig3b_sensAnalyses: output/figures/fig3b_adjusted_RRs_sensAnalysis.pdf
        fig3c_sens_analyses: output/figures/fig3b_adjusted_RRs_all_outcomes_sensAnalysis.pdf
        poissonplots_table_sensAnalyses: output/tables/tab4_poisson_rateratios_sensAnalysis.csv