version: '3.0'

expectations:
 population_size: 20000

actions:

  generate_dataset_cases:
    run: >
      databuilder:v0 
        generate-dataset analysis/dataset_definition_cases.py --output output/dataset_cases.csv.gz
    outputs:
      highly_sensitive:
        dataset_cases: output/dataset_cases.csv.gz
  
  generate_dataset_controls:
    run: >
      databuilder:v0 
        generate-dataset analysis/dataset_definition_controls.py --output output/dataset_controls.csv.gz
    outputs:
      highly_sensitive:
        dataset_controls: output/dataset_controls.csv.gz
  
  generate_dataset_lc_pre_vacc:
    run: >
      databuilder:v0 
        generate-dataset analysis/dataset_definition_longcovid_prevaccine.py --output output/dataset_lc_pre_vacc.csv.gz
    outputs:
      highly_sensitive:
        dataset_controls: output/dataset_lc_pre_vacc.csv.gz
  
  clean_the_data: 
    run: > 
      r:latest
        analysis/010_cleandata.R
    needs: [generate_dataset_cases, generate_dataset_controls]
    outputs: 
      highly_sensitive:
        cleandata: output/clean_dataset.gz.parquet 
      moderately_sensitive: 
        txt1: output/data_properties/clean_dataset_skim.txt
        txt2: output/data_properties/clean_dataset_tabulate.txt

  time_update_data: 
    run: >
      r:latest
        analysis/011_timeupdate_data.R
    needs: [clean_the_data]
    outputs: 
      highly_sensitive: 
        timedata_longcovid: output/timeupdate_dataset_lc_all.gz.parquet
        timedata_longcovid_dx: output/timeupdate_dataset_lc_dx.gz.parquet
        timedata_fracture: output/timeupdate_dataset_fracture.gz.parquet
      moderately_sensitive: 
        txt3: output/data_properties/timeupdated_dataset_skim.txt

  summarise_timedata: 
    run: >
      r:latest
        analysis/012_timeupdated_summary.R
    needs: [time_update_data]
    outputs: 
      moderately_sensitive: 
        txt4: output/data_properties/timeupdated_lc_all_tabulate.txt
        lc_all_t_plot: output/supplementary/time_updated_t_byvaccines.pdf
        lc_dx_t_plot: output/supplementary/time_updated_t_byvaccines_lc_dx.pdf

  crude_rates:
    run: >
      r:latest
        analysis/020_cruderates.R
    needs: [clean_the_data]
    outputs:
      moderately_sensitive:
        cruderates: output/tab021_crude_lc_rates.csv

  crude_rates_timeupdated:
    run: >
      r:latest
        analysis/021_cruderates_timeupdated.R
    needs: [time_update_data]
    outputs:
      moderately_sensitive:
        t_cruderates_lc_all: output/tab022_tuv_rates_lc_all.csv
        t_cruderates_lc_dx: output/tab023_tuv_rates_lc_dx.csv

  plot_incidence:
    run: >
      r:latest
        analysis/030_plotrates.R
    needs: [clean_the_data, time_update_data]
    outputs:
      moderately_sensitive:
        cuminc: output/figures/fig1_cumulative_incidence.pdf
        rawcountsplot: output/figures/fig2_raw_counts_line.pdf
        rawcount: output/figures/fig2b_raw_counts_column.pdf
        vaccinegap: output/supplementary/fig_agegap_vaccines.pdf

  poisson_rates_static:
    run: >
      r:latest
        analysis/040_poisson_regressions_staticvars.R
    needs: [clean_the_data]
    outputs:
      moderately_sensitive:
        poissonrates: output/tab023_poissonrates_static.csv

  poisson_rates_timeupdated:
    run: >
      r:latest
        analysis/041_poisson_regressions_timeupdated.R
    needs: [time_update_data]
    outputs:
      moderately_sensitive:
        poissonrates: output/tab023_poissonrates_timeupdated.csv

  poisson_plots:
    run: >
      r:latest
        analysis/042_plot_poisson_results.R
    needs: [poisson_rates_static, poisson_rates_timeupdated]
    outputs: 
      moderately_sensitive: 
        poissonplots_all: output/figures/fig3a_rate_ratios.pdf
        poissonplots_lc: output/figures/fig3b_rate_ratios_longcovid.pdf
        poissonplots_lc_adjusted: output/figures/fig3c_rate_ratios_longcovid_adjustedonly.pdf
        poissonplots_control: output/figures/fig3d_rate_ratios_controloutcome.pdf