version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format='csv.gz'
    outputs:
      highly_sensitive:
        cohort: output/input.csv.gz
    ## note: when running studies for real it is recommended to add the option --output-format='csv.gz' to the run command,
    ## and add '.gz' to the output file path, to produce the output in compressed form to reduce file size.

  describe: 
    run: r:latest analysis/report.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        cohort: output/descriptive.png
