version: '3.0'

expectations:
 population_size: 1000

actions:

  generate_dataset_cases:
    run: >
      databuilder:v0 
        generate-dataset analysis/dataset_definition_cases.py --output output/dataset_cases.csv
    outputs:
      highly_sensitive:
        dataset_cases: output/dataset_cases.csv
  
  generate_dataset_controls:
    run: >
      databuilder:v0 
        generate-dataset analysis/dataset_definition_controls.py --output output/dataset_controls.csv 
    outputs:
      highly_sensitive:
        dataset_controls: output/dataset_controls.csv
  
  generate_dataset_lc_pre_vacc:
    run: >
      databuilder:v0 
        generate-dataset analysis/dataset_definition_longcovid_prevaccine.py --output output/dataset_lc_pre_vacc.csv 
    outputs:
      highly_sensitive:
        dataset_controls: output/dataset_lc_pre_vacc.csv
  
  # quick_checks: 
  #   run: r:analysis/010_quick_checks.R
  #   needs: [generate_dataset_cases, generate_dataset_controls, generate_dataset_lc_pre_vacc]
  #   outputs:
  #      moderately_sensitive:
  #        checks: output/010_quick_checks.html


  
  # describe: 
  #   run: r:latest analysis/report.R
  #   needs: [generate_study_population]
  #   outputs:
  #     moderately_sensitive:
  #       cohort: output/descriptive.png
