version: '3.0'

expectations:
 population_size: 1000

actions:

  generate_dataset_cases:
    run: >
      databuilder:v0 
        generate-dataset analysis/dataset_definition_cases.py --output output/dataset_cases.csv.gz
    outputs:
      highly_sensitive:
        dataset_cases: output/dataset_cases.csv.gz
  
  generate_dataset_controls:
    run: >
      databuilder:v0 
        generate-dataset analysis/dataset_definition_controls.py --output output/dataset_controls.csv.gz
    outputs:
      highly_sensitive:
        dataset_controls: output/dataset_controls.csv.gz
  
  generate_dataset_lc_pre_vacc:
    run: >
      databuilder:v0 
        generate-dataset analysis/dataset_definition_longcovid_prevaccine.py --output output/dataset_lc_pre_vacc.csv.gz
    outputs:
      highly_sensitive:
        dataset_controls: output/dataset_lc_pre_vacc.csv.gz
  
  clean_the_data: 
    run: > 
      r:latest
        analysis/010_cleandata.R
    needs: [generate_dataset_cases, generate_dataset_controls]
    outputs: 
      highly_sensitive:
        cleandata: output/clean_dataset.gz.parquet 
        timedata: output/timeupdate_dataset.gz.parquet
      moderately_sensitive: 
        txt1: output/data_properties/clean_dataset_skim.txt
        txt2: output/data_properties/clean_dataset_tabulate.txt

  crude_rates:
    run: >
      r:latest
        analysis/020_cruderates.R
    needs: [clean_the_data]
    outputs:
      moderately_sensitive:
        cruderates: output/tab021_crude_lc_rates.csv
        tuvrates:  output/tab022_tuv_lc_rates.csv
  
  plot_incidence:
    run: >
      r:latest
        analysis/030_plotrates.R
    needs: [clean_the_data]
    outputs:
      moderately_sensitive:
        cuminc: output/fig1_cumulative_incidence.pdf
        rawcountsplot: output/fig2_raw_counts_bysex.pdf
  
  poisson_rates:
    run: >
      r:latest
        analysis/040_poisson_regressions.R
    needs: [clean_the_data]
    outputs:
      moderately_sensitive:
        poissonrates: output/tab023_poissonrates.csv
        irrplot: output/fig3_rate_ratios.pdf